# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
# The sketches in this repo were designed for msp432r platform
# However, msp432r does not work with Arduino CLI, so we are using
# tivac platform as a compilation test instead

name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'energia:tivac:EK-TM4C123GXL'
          platforms: |
            - name: 'energia:tivac'
              version: latest
              source-url: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_TM4C_103_index.json'
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            - source-url: https://github.com/fcooper/Energia-RSLK-Library.git
            - source-url: https://github.com/Andy4495/NewhavenOLED.git
      - name: Print the job summary
        if: ${{ inputs.message != null }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY
